(function exposeRainOrShineBazaarCatalog() {
  window["RSB_BAZAAR_VERIFIED_AT"] = "July 28, 2026";
  window["RSB_BAZAAR_FINDS"] = [
    {
      id: "leupold-bx2-8x42",
      monogram: "8x",
      name: "Leupold BX-2 Alpine HD 8x42 Binoculars",
      category: "optics",
      categoryLabel: "Birding optics",
      vendor: "Cabela's",
      price: 159.97,
      regularPrice: 229.99,
      discount: 30,
      url: "https://www.cabelas.com/shop/en/leupold-bx-2-alpine-hd-binoculars-8x42mm-3036714",
      description:
        "Waterproof HD glass with an 8x42 field-friendly balance for long mornings on the trail.",
    },
    {
      id: "nikon-prostaff-p3-8x42",
      monogram: "P3",
      name: "Nikon PROSTAFF P3 8x42 Binoculars",
      category: "optics",
      categoryLabel: "Birding optics",
      vendor: "B&H Photo",
      price: 136.95,
      regularPrice: 156.95,
      discount: 13,
      url: "https://www.bhphotovideo.com/c/product/1703396-REG/nikon_16776_8x42_prostaff_p3_binocular.html",
      description:
        "A bright, waterproof 8x42 option with a wide field of view for finding restless birds quickly.",
    },
    {
      id: "rei-650-down-jacket",
      monogram: "650",
      name: "REI Co-op 650 Down Jacket - Men's",
      category: "outerwear",
      categoryLabel: "Warm layers",
      vendor: "REI Co-op",
      price: 69.83,
      regularPrice: 129,
      discount: 45,
      url: "https://www.rei.com/product/221639/rei-co-op-650-down-jacket-mens",
      description:
        "A packable insulating layer for cold overlooks, open marshes, and patient winter stakeouts.",
    },
    {
      id: "patagonia-synchilla-snap-t",
      monogram: "ST",
      name: "Patagonia Lightweight Synchilla Snap-T Pullover",
      category: "outerwear",
      categoryLabel: "Warm layers",
      vendor: "Patagonia",
      price: 68.99,
      regularPrice: 139,
      discount: 50,
      url: "https://www.patagonia.com/product/mens-lightweight-synchilla-snap-t-fleece-pullover/25551.html?cgid=web-specials-mens",
      description:
        "Quick-drying recycled fleece for chilly dawn starts and the drive home after a fine bird.",
    },
    {
      id: "patagonia-r1-thermal",
      monogram: "R1",
      name: "Patagonia R1 Thermal Fleece Jacket - Men's",
      category: "outerwear",
      categoryLabel: "Warm layers",
      vendor: "Patagonia",
      price: 118.99,
      regularPrice: 199,
      discount: 40,
      url: "https://www.patagonia.com/product/mens-r1-thermal-fleece-jacket/40580.html?cgid=web-specials-mens-jackets-vests",
      description:
        "A breathable technical fleece that layers cleanly when a windy checklist turns into an expedition.",
    },
    {
      id: "columbia-pouration-ii",
      monogram: "PJ",
      name: "Columbia Pouration II Rain Jacket - Men's",
      category: "outerwear",
      categoryLabel: "Rain gear",
      vendor: "Columbia",
      price: 60,
      regularPrice: 110,
      discount: 45,
      url: "https://www.columbia.com/c/mens-rain-jackets/",
      description:
        "A waterproof shell deal made for the literal rain-or-shine portion of the team charter.",
    },
    {
      id: "osprey-daylite-waist-pack",
      monogram: "2L",
      name: "Osprey Daylite Waist Pack Limited Edition",
      category: "packs",
      categoryLabel: "Trail carry",
      vendor: "Osprey",
      price: 35.75,
      regularPrice: 55,
      discount: 35,
      url: "https://www.osprey.com/daylitetm-waist-pack",
      description:
        "Weather-resistant, hands-free storage for a phone, spare battery, snacks, and field notes.",
    },
    {
      id: "osprey-arcane-earth-large-day",
      monogram: "21L",
      name: "Osprey Arcane Earth Large Day Backpack",
      category: "packs",
      categoryLabel: "Trail carry",
      vendor: "Osprey",
      price: 84.5,
      regularPrice: 130,
      discount: 35,
      url: "https://www.osprey.com/US/EN/featured/sale",
      description:
        "A roomy recycled-fabric daypack for binoculars, rain layers, lunch, and one improbable detour.",
    },
  ];
})();
